[2024-11-06T06:45:38.019+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: minutely_dag.print_date_task scheduled__2024-11-06T00:50:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
